### ISSUE TITLE
Sanity check data for November 2016 election

### ISSUE THREAD

**Issue by mapsandapps** [codeforatlanta/early-voting#18]
Sanity check the site content based on what the scraper and parser are outputting (e. g. look for places that close for lunch (it doesn't handle those well) or places that supposedly close before they open) and then maybe plan to make some phone calls if anything needs confirmation.

**Comment by airbr** [comment]
Some snippets contributed to the Slack channel, I plan to practice my JSON traversal / querying skills to try and figure out any more common trends with the issues in the parses data

**Comment by mapsandapps** [comment]
Deployed the new data based on @airbr's snippets. Thanks for your help!

**Comment by airbr** [comment]
Great ^_^
