### ISSUE TITLE
`%2F` being appended to all URLs when clicking on any link

### ISSUE THREAD

**Issue by luigi** [codeforatlanta/early-voting#43]
To reproduce:

1. Load page: https://earlyvoting.codeforatlanta.org
2. Click on "Or see a list of counties"
3. The counties list does not load, and the URL gets `%2F` appended to it

**Comment by mapsandapps** [comment]
@luigi What do you mean "The correct behavior doesn't occur"?

**Comment by luigi** [comment]
Updated to be more clear!
