### ISSUE TITLE
UX: Decide how to display copy about election day polling places

### ISSUE THREAD

**Issue by mapsandapps** [codeforatlanta/early-voting#48]
It's been brought to my attention that several people will show up to an early voting location on election day. If you want to vote on election day, you need to go to your regular polling place, not any early voting one.

Please decide where and how would be the best place on the site to present this information (about a paragraph long) to the user. The site is live at https://earlyvoting.codeforatlanta.org/#/

Related to #47

**Comment by mapsandapps** [comment]
We might want to display content like this in multiple locations. I think one logical place for it is after the other dates on a polling place page, e.g. https://earlyvoting.codeforatlanta.org/#/counties/Fulton/0

It could say "Tuesday, June 20" and then "Closed" or something and link to info about how to find your regular polling place.

**Comment by Rummy222** [comment]
I would think right underneath the early eligibility box

**Comment by mapsandapps** [comment]
Assigning to myself for integration into the UI
